version: "3.9"

services:
  rsshub:
    image: diygod/rsshub
    restart: unless-stopped
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000"
      # Enter your access key here (optional)
      ACCESS_KEY: ""
      UA: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
    depends_on:
      - redis
      - browserless
    ports:
      - target: 1200
        published: 1200
        protocol: tcp
        mode: host
    networks:
      - public_access
      - redis
      - browserless

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - redis

  browserless:
    image: browserless/chrome
    restart: unless-stopped
    ulimits:
      core:
        hard: 0
        soft: 0
    networks:
      - browserless

networks:
  public_access:
    internal: false
  redis:
    internal: true
  browserless:
    internal: true

volumes:
  redis-data:
